"""Spec 42 §4 acceptance tests 1-3 against the REAL committed tutorial fixture
(`tests/data/tutorial/`, run-book 43). Skipped whole-module until the fixture
exists -- it is built on an Azure VM (run-book 43 Steps 1-5) and landed home,
not generated by this repo's test suite (spec 42 D4).

**Acceptance test 2 (spec 42 §8 amendment A2).** A1's revised test 2 asked this
module to assert the fixture's offset **equals the source catalog's row** --
"copied from the source, not invented". That is not achievable here and A2
records why: run-book 43 Step 6 runs this suite with the network disconnected,
so the source (blob) catalog is unreachable by design, and nothing shipped in
the fixture can distinguish a copied offset from an invented one. A2 therefore
**moves the source-equality gate to where the source is reachable** -- the
generator's own `_result.json` (`offset_sources` / `all_offsets_declared`,
run-book 43 Steps 2 and 4) -- and leaves this module the two checks that ARE
sound offline:

- the declaration round-trips through the declaration API (ADR 0013), and where
  a granule id carries a baseline token it agrees with that token's
  independently-derived value (D1's technique, live only on the local-CDSE
  fallback path -- MPC ids carry no token);
- the offset is one of the two physically meaningful S2 L2A values, and the
  decisive check that a wrong offset would fail is acceptance test 3's
  post-offset reflectance range.

An unconditional `== -1000` was deliberately NOT used: a generator that
hardcoded -1000 would pass it, which is exactly the failure mode A1 set out to
exclude, so it reads as a stronger check than it is.
"""

from __future__ import annotations

import os
import re

import numpy as np
import pandas as pd
import pystac
import pytest
import rasterio

import fsd
from fsd.catalog import declaration as declaration_module
from fsd.model.adapter import BaseModelAdapter
from fsd.storage import fs
from fsd.workflows import create_datacube as _create_datacube

FIXTURE_DIR = os.path.join(os.path.dirname(__file__), "data", "tutorial")
CATALOG_PATH = os.path.join(FIXTURE_DIR, "catalog.parquet")
FIELDS_PATH = os.path.join(FIXTURE_DIR, "fields.geojson")
ROI_PATH = os.path.join(FIXTURE_DIR, "roi.geojson")

pytestmark = pytest.mark.skipif(
    not os.path.exists(CATALOG_PATH),
    reason="tutorial fixture not built yet (run-book 43; spec 42 P6) -- "
           "tests/data/tutorial/catalog.parquet is absent.",
)

BANDS = ["B04", "B08", "SCL"]
MOSAIC_DAYS = 20

# D1's baseline-token technique, duplicated here (rather than importing the
# generator module) so this test has no import-time dependency on
# tests/data/tutorial/build_fixture.py's internals.
_BASELINE_RE = re.compile(r"_N(\d{2})(\d{2})_")


def _derived_offset_from_id(granule_id: str) -> int | None:
    m = _BASELINE_RE.search(str(granule_id))
    if not m:
        return None
    return -1000 if (int(m.group(1)), int(m.group(2))) >= (4, 0) else 0


# --- acceptance test 1: structural -------------------------------------------


def test_structural_one_row_per_granule_valid_cogs():
    gdf = fs.read_parquet(CATALOG_PATH)
    assert len(gdf) > 0
    assert gdf["geometry"].notna().all()
    assert gdf["id"].is_unique

    n_files = 0
    for _, row in gdf.iterrows():
        files = [f for f in str(row["files"]).split(",") if f]
        assert {f.split(".")[0] for f in files} == set(BANDS)
        for f in files:
            fp = os.path.join(row["local_folderpath"], f)
            with rasterio.open(fp) as src:
                assert src.width > 0 and src.height > 0
                assert src.driver == "GTiff"
                assert src.profile.get("compress", "").lower() == "deflate"
            n_files += 1
    assert n_files == len(gdf) * len(BANDS)


# --- acceptance test 2: radiometric (offline-checkable form, see module docstring) ---


def test_radiometric_offset_declared_and_id_consistent():
    gdf = fs.read_parquet(CATALOG_PATH)
    stamped = declaration_module.from_attrs(gdf)
    assert stamped is not None, (
        "an unstamped catalog must raise downstream (ADR 0013) -- fix the "
        "fixture, don't rely on the raise."
    )

    assert "offset" in gdf.columns
    assert gdf["offset"].notna().all()

    for _, row in gdf.iterrows():
        derived = _derived_offset_from_id(row["id"])
        if derived is not None:
            assert int(row["offset"]) == derived, (
                f"{row['id']}: catalog offset {row['offset']} disagrees with the "
                f"value its own baseline token implies ({derived})."
            )
        # The only two physically meaningful S2 L2A values (spec 32/34): -1000
        # for processing baseline >= 04.00, 0 below it. NOT asserted as -1000
        # outright -- see the module docstring / A2: a generator that hardcoded
        # -1000 would sail through that, and "copied not invented" is gated on
        # the VM instead, in the generator's _result.json.
        assert int(row["offset"]) in (0, -1000), (
            f"{row['id']}: offset {row['offset']} is neither 0 nor -1000."
        )

    # One offset for the whole fixture: it is a single MGRS tile from a single
    # archive, so a row-to-row disagreement means the selection or the copy is
    # wrong, not that the data varies.
    assert gdf["offset"].nunique() == 1, (
        f"fixture mixes offsets {sorted(gdf['offset'].unique())} -- one archive, "
        "one tile, so this should be a single value."
    )


# --- acceptance test 3: pipeline (create_training_data -> train -> run_inference) ---


class _TutorialTrivialClassifier(BaseModelAdapter):
    """A trivial 3-class model for the acceptance test -- not the tutorial's
    real DemoRF, just enough to exercise F2/F3 + inference end-to-end."""

    required_bands = ["B04", "B08"]
    n_timestamps = 0  # model-determined (spec 22): T follows the fixture's own cadence
    output_dtype = "uint8"
    output_nodata = 255
    output_band_names = ["crop_class"]
    feature_sequence = None  # -> features() below (identity: raw bands, no transform)

    def __init__(self, clf, classes):
        self.clf = clf
        self.classes = list(classes)

    def load(self):
        pass

    def features(self, data5d, band_indices):
        return data5d, band_indices

    def predict(self, X_chunk):
        pred = self.clf.predict(X_chunk)
        return np.array([self.classes.index(p) for p in pred], dtype="uint8")


def test_pipeline_create_training_data_train_and_infer(tmp_path):
    gdf = fs.read_parquet(CATALOG_PATH)
    startdate = gdf["timestamp"].min().to_pydatetime().replace(tzinfo=None)
    enddate = (gdf["timestamp"].max() + pd.Timedelta(days=1)).to_pydatetime().replace(tzinfo=None)

    export_folderpath = str(tmp_path / "training")
    td = fsd.create_training_data(
        label_polygons=FIELDS_PATH, catalog_filepath=CATALOG_PATH,
        startdate=startdate, enddate=enddate, mosaic_days=MOSAIC_DAYS,
        bands=BANDS, id_col="fid", label_col="label",
        export_folderpath=export_folderpath,
    )
    fields_gdf = fs.read_geo(FIELDS_PATH)
    n_expected_classes = fields_gdf["label"].nunique()
    assert n_expected_classes == 3

    loaded = td.load()
    data, labels = loaded["data"], loaded["labels"]
    assert data.ndim == 3  # (pixels, T, bands) -- SCL already dropped by the S2 mask
    assert data.shape[2] == 2  # B04, B08 (SCL is the mask band, mask_keep=False default)
    assert len(set(labels)) == n_expected_classes

    # Plausible post-offset reflectance range (spec 42 D1/A1): a ~1000 DN
    # un-harmonized error would push this well outside typical S2 reflectance*10000
    # values for vegetated/soil pixels.
    reflectance_like = data[data > 0]
    assert reflectance_like.size > 0
    assert reflectance_like.max() < 10000

    # --- train a trivial classifier -----------------------------------
    from sklearn.ensemble import RandomForestClassifier  # noqa: PLC0415

    X = data.reshape(data.shape[0], -1)
    clf = RandomForestClassifier(n_estimators=5, random_state=0)
    clf.fit(X, labels)
    classes = sorted(set(labels))

    # --- build one inference datacube over the fixture's own cell -----
    infer_run_folder = str(tmp_path / "infer_build")
    csv_filepath = os.path.join(infer_run_folder, "input.csv")
    _create_datacube.run_create_datacube(
        catalog_filepath=CATALOG_PATH, timestamp_col="timestamp",
        shapefilepath=ROI_PATH, id_col="id", run_folderpath=infer_run_folder,
        startdate=startdate, enddate=enddate, bands=BANDS,
        mosaic_days=MOSAIC_DAYS, csv_filepath=csv_filepath, label_col=None, cores=1,
    )
    manifest = pd.read_csv(csv_filepath)
    assert len(manifest) == 1  # one grid cell -> one datacube

    out_dir = str(tmp_path / "out")
    adapter = _TutorialTrivialClassifier(clf, classes)
    result = fsd.run_inference(adapter, csv_filepath, out_dir, progress=False)

    assert len(result.output_filepaths) == 1
    with rasterio.open(result.output_filepaths[0]) as src:
        assert src.count == 1
        assert src.nodata == 255

    catalog = pystac.Catalog.from_file(result.stac_catalog_filepath)
    items = list(catalog.get_items(recursive=True))
    assert len(items) == 1


# --- spec 48 AC10: fsd.verify_adapter, runner="local", no network ------------


class _TutorialConstantAdapter(BaseModelAdapter):
    """A trivial adapter for `verify_adapter`'s own real end-to-end test (AC10) -- no
    training needed, `verify_adapter` checks the PIPELINE (cube shape/T, band set, output
    dtype/range), not model accuracy."""

    required_bands = ["B04", "B08"]
    n_timestamps = 0  # model-determined
    output_dtype = "uint8"
    output_nodata = 255
    output_band_names = ["output"]
    feature_sequence = None

    def load(self):
        pass

    def features(self, data5d, band_indices):
        return data5d, band_indices

    def predict(self, X_chunk):
        import numpy as _np

        return _np.zeros(X_chunk.shape[0], dtype="uint8")


def test_verify_adapter_real_fixture_local_runner(tmp_path):
    """AC10: `runner="local"` works end-to-end against a local catalog -- the whole verb,
    real cube, real inference, no network (spec 36 D3 invariant 3)."""
    gdf = fs.read_parquet(CATALOG_PATH)
    startdate = gdf["timestamp"].min().to_pydatetime().replace(tzinfo=None)
    enddate = (gdf["timestamp"].max() + pd.Timedelta(days=1)).to_pydatetime().replace(tzinfo=None)

    export_folderpath = str(tmp_path / "verify_adapter")
    result = fsd.verify_adapter(
        _TutorialConstantAdapter(), roi=ROI_PATH, catalog_filepath=CATALOG_PATH,
        startdate=startdate, enddate=enddate, mosaic_days=MOSAIC_DAYS, bands=BANDS,
        export_folderpath=export_folderpath, runner="local",
    )

    assert result["pass"] is True, result["error"]
    assert result["metrics"]["cube_t"] > 0
    for name in ("datacube.npy", "metadata.pickle.npy", "output.tif", "grids.geojson"):
        assert os.path.exists(os.path.join(export_folderpath, name))
    assert not os.path.exists(os.path.join(export_folderpath, "features.npy"))  # D7 Q3

    with rasterio.open(os.path.join(export_folderpath, "output.tif")) as src:
        assert src.count == 1
        assert src.nodata == 255

    # D5: a second call with the SAME request finds the cube already landed and skips
    # straight to inference -- no rebuild (cube file untouched).
    cube_mtime = os.path.getmtime(os.path.join(export_folderpath, "datacube.npy"))
    result2 = fsd.verify_adapter(
        _TutorialConstantAdapter(), roi=ROI_PATH, catalog_filepath=CATALOG_PATH,
        startdate=startdate, enddate=enddate, mosaic_days=MOSAIC_DAYS, bands=BANDS,
        export_folderpath=export_folderpath, runner="local",
    )
    assert result2["pass"] is True
    assert os.path.getmtime(os.path.join(export_folderpath, "datacube.npy")) == cube_mtime
